/*
 * Copyright (c) 2025 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * // Some portions generated by Co-Pilot
 */

package org.eclipse.cbi.central.api;

import org.eclipse.cbi.central.core.CoreService;


/**
 * Public API service that uses the core service.
 */
public class ApiService {
    
    private final CoreService coreService;
    
    /**
     * Creates a new API service.
     */
    public ApiService() {
        this.coreService = new CoreService();
    }
    
    /**
     * Executes an operation via the API.
     * 
     * @param input the input string
     * @return the operation result
     */
    public String execute(String input) {
        return coreService.process(input);
    }
}
